version: '3.4'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "12345"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
  
  webapp:
    image: tungtrinh2003/jewelry-be:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=JewelryItem;User Id=sa;Password=12345;TrustServerCertificate=True;
    ports:
      - "8080:80"
    depends_on:
      - sqlserver
